#!/usr/bin/env python3
"""Regenerate `vinowhisper/model_digests.json` from an export on disk.

The pin has to move whenever the export toolchain does, and a pin that is
regenerated by hand is a pin that drifts silently until someone notices the
warning has been on for four releases. So this is a script, and it records the
toolchain it saw alongside the hashes so the next mismatch can tell an
optimum-intel bump apart from something worth worrying about.

    ./scripts/update_digests.py --variant npu
    ./scripts/update_digests.py --variant npu --dir /tmp/fresh-export
    ./scripts/update_digests.py --variant stateful --note "first stateful export"

Run it only against an export you have reason to trust: a fresh one, from a
clean Hugging Face cache, on a machine you control. This writes down what is
there, it does not check it. Then commit the diff, which is a list of hashes
and one toolchain block, and is meant to be read in review.
"""

import argparse
import subprocess
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from vinowhisper import config, integrity  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--variant", required=True, choices=("npu", "stateful"))
    parser.add_argument("--dir", type=Path, default=None, help="Export directory to read.")
    parser.add_argument("--model", default=config.MODEL_ID, help="Hugging Face model id.")
    parser.add_argument("--note", default="", help="Why this pin was regenerated.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be pinned, write nothing.",
    )
    args = parser.parse_args(argv)

    directory = args.dir or config.model_dir("NPU" if args.variant == "npu" else "CPU")
    if not directory.is_dir():
        print(f"no export at {directory}", file=sys.stderr)
        print(f"  run: {config.export_command(args.variant)}", file=sys.stderr)
        return 1

    before = integrity.verify(directory, args.variant, args.model)
    pin = integrity.record(
        directory,
        variant=args.variant,
        model_id=args.model,
        recorded=date.today().isoformat(),
        note=args.note or _default_note(),
    )

    print(f"{args.model} ({args.variant}) at {directory}")
    print(f"  was: {before.status} — {before.summary()}")
    print(f"  toolchain: {_render(pin.toolchain)}")
    for name, digest in pin.files.items():
        print(f"    {digest}  {name}")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return 0

    path = integrity.write_pin(pin)
    print(f"\nwrote {len(pin.files)} digests to {path}")
    print("Review the diff before committing; it is the whole security value of this file.")
    return 0


def _render(toolchain: dict[str, str]) -> str:
    return ", ".join(f"{key}={value}" for key, value in sorted(toolchain.items())) or "unknown"


def _default_note() -> str:
    """Name the commit the pin was generated at, so a stale pin is obvious."""
    try:
        head = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            cwd=Path(__file__).resolve().parent.parent,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return ""
    return f"generated at {head}"


if __name__ == "__main__":
    sys.exit(main())
